baseURL = "https://obasekisemi.github.io/obaseki.io/"
title="obaseki.io"
description = "forever learning"
theme = "hugo-coder"
languageCode = "en"
defaultContentLanguage = "en"
enableEmoji = true

[pagination]
pagerSize = 6

[markup]
[markup.highlight]
noClasses = false

[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true

[params]
author = "forever learning"
description = "Obasekis personal website"
keywords = "blog,developer,personal"
dateFormat = "January 2, 2006"
since = 2025
colorScheme = "auto"
hideColorSchemeToggle = false

[taxonomies]
category = "categories"
series = "series"
tag = "tags"



[[menu.main]]
name = "About"
weight = 1
url = "about/"

[[menu.main]]
name = "Blog"
weight = 2
url = "posts/"

[[menu.main]]
name = "Projects"
weight = 3
url = "projects/"

[[menu.main]]
name = "Contact"
weight = 4
url = "contact/"
